---
namespace: "tcharl"
name: "ansible_securehost"
version: "2.0.1"
description: "Role on top of the marvelous Freeipa collections to setup client on machines"

authors:
  - "Charlie Mordant <cmordant1@gmail.com>"

repository: "https://github.com/OsgiliathEnterprise/ansible-securehost"
documentation: "https://github.com/OsgiliathEnterprise/ansible-securehost/blob/master/README.md"
homepage: "https://github.com/OsgiliathEnterprise/ansible-securehost"
issues: "https://github.com/OsgiliathEnterprise/ansible-securehost/issues"

readme: "README.md"
license:
  - "Apache-2.0"
tags:
  - "freeipa"
  - "freeipaclient"
  - "linux"
