---
# tasks file for ansible-securehost

- name: ansible-securehost | dependences
  ansible.builtin.include_tasks: requirements.yml
  when:
   - standalone_role is defined
   - standalone_role
  tags:
    - standalone

- name: ansible-securehost | prerequisites
  ansible.builtin.import_tasks: prereq.yml

- name: ansible-securehost | configure ssh
  ansible.builtin.import_tasks: ssh.yml

- name: ansible-securehost | reset idm client
  ansible.builtin.include_tasks: freeipa-client-delete.yml
  when:
    - idm_client_group | default("") | string in group_names
    - reset_ipa_client


- name: ansible-securehost | idm prereq
  ansible.builtin.import_tasks: freeipa-prereq.yml
  when:
    - idm_group | default("") | string in group_names or idm_client_group | default("") | string in group_names

- name: ansible-securehost | idm server
  ansible.builtin.import_tasks: freeipa-server.yml
  when: idm_group | default("") | string in group_names

- name: ansible-securehost | idm client
  ansible.builtin.import_tasks: freeipa-client.yml
  when: idm_client_group | default("") | string in group_names
