---
# tasks file for ansible-securehost

- name: Requirements
  ansible.builtin.import_tasks: requirements.yml
  when:
   - standalone_role
  tags:
    - standalone

- name: Prerequisites
  ansible.builtin.include_tasks: prereq.yml

- name: Reset idm client
  ansible.builtin.include_tasks: freeipa-client-delete.yml
  when:
    - idm_client_group | default("") | string in group_names
    - reset_ipa_client

- name: Idm client
  ansible.builtin.include_tasks: freeipa-client.yml
  when: idm_client_group | default("") | string in group_names
