---
# tasks file for ansible-securehost


- name: ansible-securehost | prerequisites
  ansible.builtin.import_tasks: deps.yml
  when:
   - standalone_role is defined
   - standalone_role

- name: ansible-securehost | configure ssh
  ansible.builtin.import_tasks: ssh.yml

- name: ansible-securehost | idm server
  ansible.builtin.import_tasks: freeipa-server.yml
  when: idm_group | default("") | string in group_names

- name: ansible-securehost | unconfigure client
  ansible.builtin.import_tasks: freeipa-reset-client.yml
  when:
   - idm_client_group | default("") | string in group_names
   - reset_ipa is defined
   - reset_ipa

- name: ansible-securehost | idm client
  ansible.builtin.import_tasks: freeipa-client.yml
  when: idm_client_group | default("") | string in group_names
