---

- name: Requirements | import fail2ban role
  ansible.builtin.import_role:
    name: tcharl.fail2ban
  become: True
  when: idm_client_group | default("") | string in group_names

- name: Requirements | install ntp
  ansible.builtin.import_role:
    name: geerlingguy.ntp
  become: True
  when:
   - idm_client_group | default("") | string in group_names
   - ansible_facts['virtualization_type'] is defined
   - ansible_facts['virtualization_type'] not in ['container']

- name: Idm server
  ansible.builtin.include_tasks: freeipa-server.yml
  when: idm_group | default("") | string in group_names
