---

- name: Requirements | import epel role
  ansible.builtin.import_role:
    name: robertdebock.epel
  become: True

- name: Requirements | import bootstrap role
  ansible.builtin.import_role:
    name: robertdebock.bootstrap
  become: True

- name: Requirements | import fail2ban role
  ansible.builtin.import_role:
    name: tcharl.fail2ban
  become: True

- name: Requirements | Print all available facts
  ansible.builtin.debug:
    var: ansible_facts
    verbosity: 3

- name: requirements | install ntp
  ansible.builtin.import_role:
    name: geerlingguy.ntp
  become: True
  when:
   - ansible_facts['virtualization_type'] is defined
   - ansible_facts['virtualization_type'] not in ['container']

- name: Idm server
  ansible.builtin.include_tasks: freeipa-server.yml
  when: idm_group | default("") | string in group_names
