---

- name: Prereq | install package needed to gather ip and hostname
  ansible.builtin.package:
    name: "{{ item }}"
  with_items:
    - iproute
    - hostname
    - NetworkManager
    - systemd-networkd
    - systemd-resolved
  become: True

- name: Prereq | Disables all ipv6
  ansible.posix.sysctl:
    name: net.ipv6.conf.all.disable_ipv6
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes
  become: yes

- name: Prereq | Disables default ipv6
  ansible.posix.sysctl:
    name: net.ipv6.conf.default.disable_ipv6
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes
  become: yes

- name: Prereq | Start Systemd Networkd service
  ansible.builtin.service:
    name: systemd-networkd
    enabled: True
    state: started
  become: true

- name: Prereq | Start Systemd Resolved service
  ansible.builtin.service:
    name: systemd-resolved
    enabled: True
    state: started
  become: true

- name: Prereq | Start NetworkManager service
  ansible.builtin.service:
    name: NetworkManager
    enabled: True
    state: started
  become: true
