---
- name: Converge
  hosts: all
  vars:
    standalone_role: False
    secure_logs: False
    idm_preferred_nic: "ens5"
    preferred_nic: "ens5"
    company_domain: osgiliath.test
  roles:
    - role: tcharl.ansible_securehost
