---
- name: Converge
  hosts: all
  tasks:
    - name: "Include Ansible securehost"
      include_role:
        name: "ansible-securehost"
      vars:
        company_domain: osgiliath.test
        secure_logs: False
