---
- name: Converge
  hosts: client.osgiliath.test
  vars:
    idm_preferred_nic: "eth1"
    company_domain: osgiliath.test
    secure_logs: False
    standalone_role: False
    preferred_nic: "eth1"
  roles:
    - role: tcharl.ansible_securehost
