---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
    roles-path: ${MOLECULE_PROJECT_DIRECTORY}/../community
    requirements-file: requirements-collections.yml
    collections-path: ${MOLECULE_PROJECT_DIRECTORY}/../community-collections
driver:
  name: vagrant
  provider:
    name: libvirt
lint: |
  set -e
  yamllint .
  flake8
  ANSIBLE_ROLES_PATH=${MOLECULE_PROJECT_DIRECTORY}/../community ANSIBLE_COLLECTIONS_PATH=${MOLECULE_PROJECT_DIRECTORY}/../community-collections ansible-lint
platforms:
  - name: idm.osgiliath.test
    box: fedora/34-cloud-base
    provider_options:
      driver: '"kvm"'
      cpus: 2
      memory: 2048
    interfaces:
      - auto_config: true
        network_name: private_network
        type: dhcp
    groups:
      - ipaservers
  - name: client.osgiliath.test
    box: fedora/34-cloud-base
    provider_options:
      driver: '"kvm"'
      cpus: 2
      memory: 2048
    interfaces:
      - auto_config: true
        network_name: private_network
        type: dhcp
    groups:
      - ipaclients
provisioner:
  name: ansible
#  config_options:
#    defaults:
#      forks: 20
#   ssh_connection:
#     pipelining: true
#      ssh_args: -o ControlMaster=auto -o ControlPersist=6000s
  env:
    ANSIBLE_ROLES_PATH: ${MOLECULE_PROJECT_DIRECTORY}/../community:${ANSIBLE_ROLES_PATH}:${MOLECULE_PROJECT_DIRECTORY}/..
    ANSIBLE_COLLECTIONS_PATH: ${ANSIBLE_COLLECTIONS_PATH}:${MOLECULE_PROJECT_DIRECTORY}/../community-collections
verifier:
  name: testinfra
  env:
    PYTHONWARNINGS: "ignore:.*U.*mode is deprecated:DeprecationWarning"
  options:
    v: 1
scenario:
  name: kvm
  test_sequence:
    - dependency
    - lint
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
 #   - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
