---
- name: Converge
  hosts: all
  vars:
    standalone_role: False
    secure_logs: False
    company_domain: osgiliath.test
    idm_preferred_nic: "enp0s5"
    preferred_nic: "enp0s5"
  roles:
    - role: tcharl.ansible_securehost
