---
- name: Prepare idm
  hosts:
    - idm.osgiliath.test
  tasks:
    - name: "install fedora ansible prerequisites"
      ansible.builtin.raw: dnf install -y python3 python3-libdnf5
      changed_when: false
      become: true
    - include_role:
        name: tcharl.freeipa_server
      vars:
        preferred_nic: "eth1"
        standalone_role: True
        firewalld_zone: "internal"
        company_domain: "osgiliath.test" # That server's hostname will be idm."{{ company_domain }}"
        company_realm_password: '123ADMin'
        company_ad_password: '123ADmPass'

- name: Prepare
  hosts:
    - client.osgiliath.test
  tasks:
    - name: "install fedora ansible prerequisites"
      ansible.builtin.raw: dnf install -y python3 python3-libdnf5
      changed_when: false
      become: true
    - include_role:
        name: tcharl.ansible_securehost
        tasks_from: requirements.yml
      vars:
        preferred_nic: "eth1"
        standalone_role: True
        firewalld_zone: "internal"
        company_domain: "osgiliath.test" # That server's hostname will be should ipa."{{ company_domain }}"
        company_realm_password: '123ADMin'
        company_ad_password: '123ADmPass'
